### ISSUE TITLE
File signing

### ISSUE THREAD

**Issue by elimisteve** [cathalgarvey/go-minilock#13]
Is it possible to sign files with go-minilock? I don't see anything about signing in the miniLock README, but it's public key crypto so I assume it's possible... Thanks.

**Comment by elimisteve** [comment]
Oops, I dug deeper and see that `minilock.DecryptFileContents()` indeed returns the sender as parsed from the received and decrypted file. My mistake! Glad file signing is there, and is guaranteed to be.

**Comment by cathalgarvey** [comment]
Not signing per-se, and in fact this construction does not allow signing. Messages are *authenticated* between sender and recipient, so for a given sender:recipient pair it can be known that the sender is authentic, by the recipient. However, this is *repudiable* because the recipient can forge a message to themselves from any sender.

In other words, the only people who can craft a legit-looking message to you are the real owners of their respective IDs, and you. So of you receive revolutionary propaganda from me and did not make it yourself, you know I sent it. But if you emerge saying I sent you revolutionary agitprop, I can deny it because you can easily forge it.

Hope that helps!

On 18 June 2016 03:16:45 IST, Steven Phillips <notifications@github.com> wrote:
>Oops, I dug deeper and see that `minilock.DecryptFileContents()` indeed
>returns the sender as parsed from the received and decrypted file. My
>mistake! Glad file signing is there, and is guaranteed to be.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cathalgarvey/go-minilock/issues/13#issuecomment-226916324

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elimisteve** [comment]
@cathalgarvey Perfect, thank you!

**Comment by elimisteve** [comment]
@cathalgarvey Relatedly, is it possible to encrypt a file with one's private key so that it can be decrypted with one's public key, like with normal public key crypto?

Context: I am trying to craft a chat message that anyone can verify came from me _without them being one of the original recipients_. I symmetrically encrypt a message, other people in a chat room have that key, and so they can decrypt the message... but how do they know it came from me and not one of the other people in the chat room?

I get that signing isn't part of miniLock, but my current idea for a work-around is: if I can encrypt a known value with my private key, and, after peeling off the symmetric crypto layer, others in that chat room can see that the message's ID matches the value they decrypt, like this:

Original message:

> secret_box({"id": "c871e3a6-c186-4478-9d67-b039b95597a8", "msg": "What's up?", "verify": myMiniLockPrivateKey("c871e3a6-c186-4478-9d67-b039b95597a8")}

Now there needs to be more to it than this, since someone shouldn't be able to take a message's `id`, stick it in another message alongside `myMiniLockPrivateKey(messageID)`, so that the IDs check out, but the new message didn't actually come from me -- actually, I could just encrypt the hash of the `msg` instead of encrypting the `id` -- but anyway, if I can encrypt with a miniLock private key, I can leverage these kinds of constructions.

Thanks!

**Comment by cathalgarvey** [comment]
I'm afraid the idea of a generally-verifiable signature without compromising key ownership is something that miniLock's primitives simply aren't designed for. It's possible that some circuitous arrangement could be won that would look OK to you and I (though, honestly, I don't understand precisely what you're suggesting here), but thrn you'd be into territory where you're breaking assumptions of miniLock and might fall foul of subtleties in the primitives.

If you haven't already, I suggest reading the documentation on NaCl itself (look up "Networking and Cryptography Library"), in particular the guarantees offered by the "box" and "secret box" primitives. They underly miniLock, and were deliberately designed to be authenticated but repudiable... in other words, not to be signatures.

NaCl does offer a signing primitive, but it hasn't been ported to Go, and it's not part of miniLock at all.

On 5 July 2016 02:48:58 IST, Steve Phillips <notifications@github.com> wrote:
>@cathalgarvey Relatedly, is it possible to encrypt a file with one's
>private key so that it can be decrypted with one's public key, like
>with normal public key crypto?
>
>Context: I am trying to craft a chat message that anyone can verify
>came from me _without them being one of the original recipients_. I
>symmetrically encrypt a message, other people in a chat room have that
>key, and so they can decrypt the message... but how do they know it
>came from me and not one of the other people in the chat room?
>
>I get that signing isn't part of miniLock, but my current idea for a
>work-around is: if I can encrypt a known value with my private key,
>and, after peeling off the symmetric crypto layer, others in that chat
>room can see that the message's ID matches the value they decrypt, like
>this:
>
>Original message:
>
>> secret_box({"id": "c871e3a6-c186-4478-9d67-b039b95597a8", "msg":
>"What's up?", "verify":
>myMiniLockPrivateKey("c871e3a6-c186-4478-9d67-b039b95597a8")}
>
>Now there needs to be more to it than this, since someone shouldn't be
>able to take a message's `id`, stick it in another message alongside
>`myMiniLockPrivateKey(messageID)`, so that the IDs check out, but the
>new message didn't actually come from me -- actually, I could just
>encrypt the hash of the `msg` instead of encrypting the `id` -- but
>anyway, if I can encrypt with a miniLock private key, I can leverage
>these kinds of constructions.
>
>Thanks!
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cathalgarvey/go-minilock/issues/13#issuecomment-230372035

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
