### ISSUE TITLE
Public key (miniLock ID)

### ISSUE THREAD

**Issue by Fastidious** [cathalgarvey/go-minilock#16]
How can I generate a public key (miniLock ID) to share with others?

**Comment by cathalgarvey** [comment]
Stupid as this may sound, there is no mode to simply display a key for a given email/passphrase. However, if you encrypt something, the ID (Key) will be displayed on the terminal.

On 5 January 2018 18:33:18 GMT+00:00, Fastidious <notifications@github.com> wrote:
>How can I generate a public key (miniLock ID) to share with others?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cathalgarvey/go-minilock/issues/16

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Fastidious** [comment]
@cathalgarvey that works!
