### ISSUE TITLE
Re-enter passphrase

### ISSUE THREAD

**Issue by Fastidious** [cathalgarvey/go-minilock#17]
If I have a typo on my password, the encrypted file information will be gone forever. Asking twice for a password on encryption is something that is needed.

**Comment by cathalgarvey** [comment]
Hey @Fastidious - When you encrypt with `minilock-cli`, it will display the key used for encryption on the terminal. You should verify that this is the correct key. If you intend to delete the cleartext data, I'd suggest doing a trial-decryption first to make sure.

Implementing double-passphrase input, as an optional flag-to-enable, is something I'd be happy to receive a PR for, but I don't see the need as long as the key is verified, for now.
