### ISSUE TITLE
Crash in minilock.EncryptFileContents with empty `fileContents`

### ISSUE THREAD

**Issue by sahib** [cathalgarvey/go-minilock#8]
Hi there,

I managed to crash this nice library. It occurred to me when attempting to encrypt an empty file.
Here's a minimal test program, backtrace included:

    https://gist.github.com/sahib/cac562333a0385856c8d

I'm using the latest ``master`` branch (on Linux if that matters).
Seems you're missing some kind of a clamp in [taber](https://github.com/cathalgarvey/go-minilock/blob/master/taber/box_encrypt.go#L124):

```go
    max_length := FILENAME_BLOCK_LENGTH + (num_chunks * BLOCK_LENGTH)
    // make-len will get negative for make_length < BLOCK_LENGTH...
    ciphertext = make([]byte, max_length-BLOCK_LENGTH, max_length)
```

**Comment by cathalgarvey** [comment]
Thanks Chris! Really appreciate the help finding bugs. Taber is the hairiest part of the code by far, too.

Will try to address this tomorrow. :)

On 20 December 2015 23:02:08 GMT+00:00, Chris Pahl <notifications@github.com> wrote:
>Hi there,
>
>I managed to crash this nice library. It occurred to me when attempting
>to encrypt an empty file.
>Here's a minimal test program, backtrace included:
>
>    https://gist.github.com/sahib/cac562333a0385856c8d
>
>I'm using the latest ``master`` branch (on Linux if that matters).
>Seems you're missing a ``min()`` in
>[taber](https://github.com/cathalgarvey/go-minilock/blob/master/taber/box_encrypt.go#L124):
>
>```go
>    max_length := FILENAME_BLOCK_LENGTH + (num_chunks * BLOCK_LENGTH)
>    // make-len will get negative for make_length < BLOCK_LENGTH...
>    ciphertext = make([]byte, max_length-BLOCK_LENGTH, max_length)
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cathalgarvey/go-minilock/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sahib** [comment]
Hey, there! Any news on this?

 If not, I might try to do a pull request when I find the time.

**Comment by cathalgarvey** [comment]
Thanks for reminding me! Just checking my code out, will add test case and fix it. :)

**Comment by cathalgarvey** [comment]
Hope this fixes the problem, I put a zero-length check in taber and minilock. :)

**Comment by sahib** [comment]
Cool, thanks. I can confirm it is fixed now.

I somehow expected that you'd just make minilock also encrypt empty files, so I don't need to have a check if the file is empty anymore, but the main point is that is does not crash anymore.
(Im not sure if an empty minilock file is possible (probably) or a good idea (less probable)).

:+1:

**Comment by cathalgarvey** [comment]
Hmm, well I'm midway through a code tidy-up, mostly Linter stuff. But, it's re-familiarising me with how things tick and I'll think about whether empty encryption makes sense. I'd just assumed it would represent an error to encrypt an empty slice, but perhaps there are uses for an empty but authenticated encrypt/decrypt operation.

My instinct is still to exclude them, because if people end up using them for "tiny auth" and omit nonces or timestamps from the plaintext, then they're vulnerable to replay because miniLock itself provides no explicit way to tell identical plaintexts apart. You could use the ephemeral key ID as a nonce, I guess, but it's a bad pattern. Can you anticipate any uses for empty encryption that might warrant it?

**Comment by sahib** [comment]
My point of view was as a user of the library - where it's tedious to check between empty input (handle differently, i.e. just leave as is) and other input (encrypt it). Same for the decryption code (fails if running on empty file, since no magic bytes in front).

Apart from this very general case, it might sometimes desirable to always have a valid minilock header in front, so code can figure out if it was encrypted by checking the magic bytes. In case of empty files you could not be sure. Think of a protocol where only the first message is not encrypted in order to establish a session, but all other messages are ignored if they aren't encrypted.

From my perspective, the current way it works is no big problem (if at all) since it could be solved by writing a bit of wrapper code. In any case it should be clearly documented that len(slice) is supposed to be > 0. Your security concerns look valid to me, so I'd value security over usability in this case. Alternatively you might introduce API that handles those special cases seamlessly.

Hope that made sense. No coffee yet.
